name: CI/CD Integration 💥

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        

      - name: Pull latest code into DCxProject directory
        run: |
          cd /var/www/DCxProject  
          git fetch origin main    
          git reset --hard origin/main 
          
      - name: Fix Storage Permissions
        run: |
          sudo chmod -R 775 /var/www/DCxProject/storage
          sudo chmod -R 775 /var/www/DCxProject/bootstrap/cache
